### ISSUE TITLE
明细表格el-table如何设计

### ISSUE THREAD

**Issue by newlinbaolin** [jjxliu306/vue-form-design#2]
如题

**Comment by jjxliu306** [comment]
目前只做了动态数据的添加修改el-table。考虑后面加一个纯展示性的el-table。



jjxliu306@163.com
 
发件人： 林宝林
发送时间： 2020-12-11 15:32
收件人： jjxliu306/vue-form-design
抄送： Subscribed
主题： [jjxliu306/vue-form-design] 明细表格el-table如何设计 (#2)
如题

**Comment by newlinbaolin** [comment]
OK。期待你完成后我再整合进我的项目。



林宝林
 
发件人： jjxliu306
发送时间： 2020-12-21 09:12
收件人： jjxliu306/vue-form-design
抄送： 林宝林; Author
主题： Re: [jjxliu306/vue-form-design] 明细表格el-table如何设计 (#2)
目前只做了动态数据的添加修改el-table。考虑后面加一个纯展示性的el-table。 



jjxliu306@163.com 

发件人： 林宝林 
发送时间： 2020-12-11 15:32 
收件人： jjxliu306/vue-form-design 
抄送： Subscribed 
主题： [jjxliu306/vue-form-design] 明细表格el-table如何设计 (#2) 
如题
