### ISSUE TITLE
表单构建

### ISSUE THREAD

**Issue by fanaishan** [jjxliu306/vue-form-design#3]
麻烦问下,在项目中如何通过json构建表单,达到预览的效果

**Comment by jjxliu306** [comment]
1.0.11-beta版本已经发布，放开了VueDragFormBuild组件，专门用来进行表单展示和数据填写，可以参考example和README



jjxliu306@163.com
 
发件人： afanda
发送时间： 2020-12-19 10:52
收件人： jjxliu306/vue-form-design
抄送： Subscribed
主题： [jjxliu306/vue-form-design] 表单构建 (#3)
麻烦问下如何通过json构建表单
